ALTER TABLE TICKETS
ADD FOREIGN KEY (VIN)
REFERENCES VEHICLES(VIN);

ALTER TABLE VEHICLES
ADD FOREIGN KEY (OwnerLicenseID)
REFERENCES DRIVERS(LicenseID);

ALTER TABLE TICKETS
ADD FOREIGN KEY (LicenseID)
REFERENCES DRIVERS(LicenseID);
